export enum RouteNames {
  HOME = 'HOME',
  PROJECT = 'PROJECT',
  PROFILE = 'PROFILE',
  USER_INFO = 'USER_INFO',
  USER_REQUESTS = 'USER_REQUESTS',
  USER_PROJECTS = 'USER_PROJECTS',
  USER_SKILLS = 'USER_SKILLS',
  FAQ = 'FAQ',
  CONTACTS = 'CONTACTS',
  PROJECT_DETAILS = 'PROJECT_DETAILS',
  PROJECT_REQUESTS_LIST = 'PROJECT_REQUESTS_LIST',
}
