export enum MutationTypes {
  SET_PROJECT_LIST = 'SET_PROJECT_LIST',
  SET_LOADING = 'SET_LOADING',
  SET_ERROR = 'SET_ERROR',
  SET_FILTERS = 'SET_FILTERS',
  SET_FILTER_OPTIONS = 'SET_FILTER_OPTIONS',
}
